### PR TITLE
SourceMod 1.12 Migration

### PR DESCRIPTION
**Pull request by Alienmario**
- updated CI + Readme
- moved gpGlobals variable to main plugin space (unused warning)
- fixed macros (CONF_*, assert)
- replaced entindex-enthandle conversion stocks with natives
- removed CookieCompat in addon_earbleed
- replaced Cookie utils with new methodmap accessors
- with that done, addon_killsounds will not store the default value in cookies anymore
- turned addon_scoring into a placeholder for new implementation
- removed obsolete timer returns

### CODE REVIEW

**Comment by Alienmario** [comment]
Investigating crashing on linux: https://crash.limetech.org/7afrqsdsuw4y.

**Comment by Alienmario** [comment]
There is a regression that occurs when hooking UTIL_GetLocalPlayer on Linux.
https://github.com/ampreeT/SourceCoop/blob/698862d3aab8f96fdd80fb1680baac8fec5f7179/scripting/include/srccoop/entitypatch.inc#L136-L158
Returning "MRES_Ignored" makes the original function crash nearby accessing of `gpGlobals->maxClients`.
Superceding with `DHookSetReturn(hReturn, -1); return MRES_Supercede;` instead does not crash.

**Comment by Alienmario** [comment]
Minimal example

lp_test.games.txt
```
"Games"
{
	"bms"
	{
		"Functions"
		{
			"UTIL_GetLocalPlayer"
			{
				"signature"	"UTIL_GetLocalPlayer"
				"callconv"	"cdecl"
				"return"	"cbaseentity"
			}
		}
		"Signatures"
		{
			"UTIL_GetLocalPlayer" // CBasePlayer UTIL_GetLocalPlayer(void)
			{
				"windows"	"\xA1\x2A\x2A\x2A\x2A\x8B\x40\x14\x83\xF8\x01\x7E\x2A\xA1\x2A\x2A\x2A\x2A"
				"linux" 	"@_Z19UTIL_GetLocalPlayerv"
			}
		}
	}
}
```
lp_test.sp
```
#include <sourcemod>
#include <dhooks>

#pragma newdecls required
#pragma semicolon 1

#define GAMEDATA_NAME "lp_test.games"
DynamicDetour hkUTIL_GetLocalPlayer;

public void OnPluginStart()
{
	GameData pGameConfig = LoadGameConfigFile(GAMEDATA_NAME);
	if (pGameConfig == null)
		SetFailState("Couldn't load game config: \"%s\"", GAMEDATA_NAME);
	
	hkUTIL_GetLocalPlayer = DynamicDetour.FromConf(pGameConfig, "UTIL_GetLocalPlayer");
	if (hkUTIL_GetLocalPlayer == null)
		SetFailState("Couldn't create hook");

	if (!hkUTIL_GetLocalPlayer.Enable(Hook_Pre, Hook_UTIL_GetLocalPlayer))
		SetFailState("Couldn't enable pre detour hook");

	pGameConfig.Close();
}

public MRESReturn Hook_UTIL_GetLocalPlayer(DHookReturn hReturn)
{
	PrintToServer("Hook_UTIL_GetLocalPlayer");
	return MRES_Ignored;
}
```

**Comment by ampreeT** [comment]
> While sm devs are looking into the issue, we can target 1.12 7163, which has all the features minus the updated hooking library.

We'll need to update the install scripts to install the specific version of SourceMod required rather than the latest version temporarily until the hooking library is fixed.

**Comment by ampreeT** [comment]
Looks good to me!

**Comment by Alienmario** [comment]
> > While sm devs are looking into the issue, we can target 1.12 7163, which has all the features minus the updated hooking library.
> 
> We'll need to update the install scripts to install the specific version of SourceMod required rather than the latest version temporarily until the hooking library is fixed.

Alright then, when you're ready, please merge this and update the scripts. Hardcoding the links should be fine.

**Review by ampreeT — APPROVED** [review]

**Pull request merged**
