### PR TITLE
Fix mounting ladders with many players

### PR DESCRIPTION
**Pull request by Balimbanana**
This fix is based on the SDK code, with a fixed trace that ignores players. I had attempted to create a detour of CHL2GameMovement::Findladder which is the function that is being used in Black Mesa as CBlackMesaGameMovement has a BaseClass of CHL2GameMovement it uses the same function. But I can't seem to get a signature that works.

### CODE REVIEW

**Comment by Alienmario** [comment]
Found some issues https://www.youtube.com/watch?v=zMtAJ6Sa98M
Would also prefer the snap-in to stay smooth if the ladder is not being used by anyone.

**Review by Alienmario — CHANGES_REQUESTED** [review]
^

**Comment by Balimbanana** [comment]
Yes, I see the problem, testing out a few things, then I'll push what seems to be the most accurate.
Also, for the question of smooth transition with no players, as stated in playerpatch.inc:

	// By using m_afButtonPressed, this is actually ignored by the game code if players mount ladders the normal way as it calls ::SwallowUseKey()

**Review by Alienmario — APPROVED** [review]

**Comment by Alienmario** [comment]
I'm putting it on the server to see if we find potential issues with multiple players.

**Comment by Balimbanana** [comment]
Oh nice, I didn't know when SM added `Vector = Vector` support. It was giving errors a while back so I assumed it just never was going to be implemented. Always doing float[0] = float[0], [1] = [1], [2] = [2].

**Pull request merged**
