### PR TITLE
Survival Mode

### PR DESCRIPTION
**Pull request by Balimbanana**
RE: #68

### CODE REVIEW

**Comment by Balimbanana** [comment]
Mostly added the !stuck back because with survival mode people really need to be able to get out of being stuck without suiciding.

**Comment by Alienmario** [comment]
Sorry for taking so long. Went on a refactoring journey to keep the codebase sane. The solution I settled with needed a recent SM version (global/cyclic methodmap access), so I've went ahead and also added a custom LevelInit hook. (Fixes #58).
Will post code when ready.
..
(Closes #31)

**Comment by Alienmario** [comment]
So, I've moved majority of survival stuff to manager_survival.inc. Some of it was redone, added convar sourcecoop_survival_spawn_timeout. In the process I might have deleted some things I thought were unnecessary. Let me know if I need to add something back. Manager and SurvivalManager are methodmaps now, thanks to newer Sourcepawn builds allowing access to it from anywhere, regardless what's defined first.
LevelInit hook is fully custom DHook.
You should use a recent or latest SM version now to compile.

Current issues:
- Needs to be retested
- Server Ragdolls are sometimes iffy, spawn with wrong velocity or position.
- Revive should move its location with ragdolls (better yet parent to)
- Sometimes spectator camera goes crazy before survival restart
- Survival mode doesn't react to team changes and disconnects, locks up
- Spectating players trigger touch events when flying through the map

Using observer mode while still alive is kind of clever, however if these issues can't be solved, we might have to change teams instead.

**Comment by Alienmario** [comment]
As for progress bars, the game does have [nav_progress](https://forums.alliedmods.net/showthread.php?t=184088&highlight=progress), though it's hardly usable and not so nice. Plus it blocks player inputs.

The nicest option we probably have is a custom animated sprite. I've only seen this done in HL2DM. It's an entity or temp ent displayed to select clients. Its material has multiple frames, one per percentage. The displayed frame shows the current progress. It starts mostly transparent and that transparency gets replaced by solid color as the bar progresses.

**Comment by Balimbanana** [comment]
I should be able to look in to it today, I think I will remove the sprite entirely, since the ragdoll is actually accurate now.
For the progress bar, I was thinking of using a beam sprite that can grow from left to right potentially. Although, if you have that sprite material somewhere, that would make it much simpler.

I have changed sourcecoop_revive to FindTarget, and have added a ClientFade of blue to the revived target, and moved a few things around.

**Comment by Balimbanana** [comment]
I have ***a*** version of a progress bar that I wrote, it isn't quite as good as I want it to be though, kind of hard with the limited tempents setup there.
Maybe it could work by SetTransmit on a beam entity and moving it instead of redrawing it.

**Comment by Balimbanana** [comment]
Here is what the progress bar looks like as of current: 
image

Following the player eye angles with configuration of width, color, time to complete, etc. If the width is too wide, you will have to adjust the distance from player, it has a default value, but it is configurable if needed.

**Comment by Alienmario** [comment]
Alright, I think it's safe to start wrapping up.

Only 2 issues I got from last testing.
- Couldn't hear the sound when respawning after being revived.
- When dead, after rejoining, your player model is visible and t-posing. Joining spectate and back fixes it.

Current version is playable on 49.12.103.55:27015
You can start a vote to toggle survival mode.

**Comment by Balimbanana** [comment]
I have moved the revive sound to be after the revived is teleported as they are most likely at whatever origin the spawnpoint is at and out of range at the moment of revive.

I added RENDERFX_FADE_FAST to HandlePlayerSpawn of the survival manager. Can't use RenderMode as it is constantly reset, but RenderFX is not. It is safely reset to 0 on actual spawn anyways, so it being incorrectly set *shouldn't* be an issue.

Do you want the progress bar stock to be added to any particular util, or make a forward potentially?

**Comment by SHOUBISHOCK** [comment]
is it possible to add a beacon effect something which show indication of ragdoll to revive to helps highlight dead body position to other players.

**Pull request merged**
