### PR TITLE
CI with Github Actions to build nightlies archives 

### PR DESCRIPTION
**Pull request by yarik2720**
Adding this workflow allows to download already compiled plugins with needed files in archive.
Suddenly this requires to change project path hierarchy

### CODE REVIEW

**Comment by Alienmario** [comment]
I appreciate the effort, but the project structure is intentional to aid development.
It should be the build script's job to organize the output archive.

**Comment by yarik2720** [comment]
@Alienmario now switched to another builder, that accepts current file hierarchy

**Comment by Alienmario** [comment]
Looking good, permission to experiment? (I'm a ci noob)

**Comment by yarik2720** [comment]
@Alienmario it start automatically work once this is in your repository, even not in master branch. CI will make build (based by yml settings) on every commit push and pull requests

**Comment by Alienmario** [comment]
Yeah I'm aware, was more talking about the yml editing.
Anyway I'll merge it in now and see if I can expand on it after.
This will surely make many people happy, thank you.

**Pull request merged**
